export const styles = {
  dashboardContainer: {
    maxWidth: '1200px',
    margin: '0 auto',
  },
  card: {
    background: 'white',
    borderRadius: '12px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    marginBottom: '24px',
  },
  controlBar: {
    padding: '12px 20px',
    borderBottom: '1px solid #e9ecef',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '10px',
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: 600,
    fontFamily: 'Segoe UI, sans-serif',
  },
  controlActions: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  inputGroupLabel: {
    fontSize: '13px',
    color: '#495057',
    whiteSpace: 'nowrap',
    fontFamily: 'Segoe UI, sans-serif',
  },
  inputGroupInput: {
    padding: '6px 10px',
    border: '1px solid #e9ecef',
    borderRadius: '6px',
    fontSize: '13px',
    fontFamily: 'Segoe UI, sans-serif',
    outline: 'none',
    '&:focus': {
      borderColor: '#6D94C5',
    },
  },
  btn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '8px 12px',
    background: 'white',
    border: '1px solid #e9ecef',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    whiteSpace: 'nowrap',
    transition: 'all 0.3s ease',
    fontFamily: 'Segoe UI, sans-serif',
    outline: 'none',
    textDecoration: 'none',
    '&:hover:not(:disabled)': {
      background: '#f8f9fa',
    },
    '&:disabled': {
      opacity: 0.6,
      cursor: 'not-allowed',
    },
  },
  btnPrimary: {
    background: '#6D94C5',
    color: 'white',
    border: 'none',
    '&:hover:not(:disabled)': {
      background: '#5a7da8',
    },
  },
  cardBody: {
    padding: '20px',
    position: 'relative',
  },
  legendToggles: {
    display: 'flex',
    gap: '20px',
    alignItems: 'center',
    marginBottom: '16px',
    flexWrap: 'wrap',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    userSelect: 'none',
    padding: '6px 12px',
    borderRadius: '20px',
    transition: 'all 0.2s ease',
    '&:hover': {
      background: '#f8f9fa',
    },
  },
  legendItemInactive: {
    opacity: 0.5,
  },
  legendIndicator: {
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    border: '3px solid',
    transition: 'all 0.3s ease',
    flexShrink: 0,
  },
  legendIndicatorCredit: {
    borderColor: 'rgb(75, 192, 192)',
    background: 'rgb(75, 192, 192)',
  },
  legendIndicatorDebit: {
    borderColor: 'rgb(255, 99, 132)',
    background: 'rgb(255, 99, 132)',
  },
  legendIndicatorTotal: {
    borderColor: 'rgb(16, 185, 129)',
    background: 'rgb(16, 185, 129)',
  },
  legendIndicatorInactive: {
    background: 'white',
  },
  legendLabel: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#333',
    fontFamily: 'Segoe UI, sans-serif',
  },
  chartArea: {
    position: 'relative',
    height: '400px',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(255,255,255,0.9)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  spinner: {
    border: '3px solid #e9ecef',
    borderTop: '3px solid #6D94C5',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    animation: 'spin 1s linear infinite',
  },
  buFilterContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  buFilterCards: {
    display: 'flex',
    gap: '8px',
  },
  buFilterCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    background: 'white',
    border: '2px solid #e9ecef',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    fontSize: '13px',
    fontFamily: 'Segoe UI, sans-serif',
    userSelect: 'none',
    '&:hover': {
      background: '#f8f9fa',
      borderColor: '#6D94C5',
    },
  },
  buFilterCardSelected: {
    background: '#6D94C5',
    borderColor: '#6D94C5',
    color: 'white',
  },
  buCheckbox: {
    width: '18px',
    height: '18px',
    border: '2px solid #dee2e6',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
    flexShrink: 0,
  },
  buCheckboxSelected: {
    borderColor: 'white',
    background: 'white',
  },
  buCheckboxInner: {
    width: '10px',
    height: '10px',
    background: '#6D94C5',
    borderRadius: '2px',
    opacity: 0,
    transition: 'opacity 0.2s ease',
  },
  buCheckboxInnerSelected: {
    opacity: 1,
  },
};

